apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-app-quota
  namespace: nginx-app
spec:
  hard:
    pods: "10"
    requests.cpu: "500m"
    requests.memory: "512Mi"
    limits.cpu: "2"
    limits.memory: "1Gi"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: nginx-app-limits
  namespace: nginx-app
spec:
  limits:
    - type: Container
      default:
        cpu: "200m"
        memory: "128Mi"
      defaultRequest:
        cpu: "50m"
        memory: "64Mi"
